# Generated by Django 3.1 on 2023-08-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bdiscription',
            new_name='bb',
        ),
    ]
